// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonarchMediaLLC.ApiService.Data;

#nullable disable

namespace MonarchMediaLLC.ApiService.Migrations
{
    [DbContext(typeof(MonarchDbContext))]
    [Migration("20260701131308_AddImagePathToProjects")]
    partial class AddImagePathToProjects
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("MonarchMediaLLC.Shared.ProjectSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TechStack")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProjectSummaries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A custom architectural web portal featuring high-performance image lightboxes and 2D/3D floorplan matrices.",
                            ImagePath = "",
                            TechStack = "Astro • TS • Tailwind",
                            Title = "Southard Homes",
                            Url = "https://www.southardhomesllc.com/"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Corporate communication platform optimizing structural local SEO and service maps for the Wabash Valley area.",
                            ImagePath = "",
                            TechStack = "Astro • TS • Tailwind",
                            Title = "Quality Electric of Indiana",
                            Url = "https://qualityelectricofindiana.com/"
                        });
                });

            modelBuilder.Entity("MonarchMediaLLC.Shared.TeamMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TeamMembers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Steers business strategy, client partnerships, and corporate vision to help local businesses establish clear brand dominion.",
                            ImagePath = "images/team/Christa.jpg",
                            Name = "Christa Summerville",
                            Role = "CEO & Executive Director"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Architects ultra-performant modern web ecosystems, bridging the gap between blazing-fast JAMstack frontends and complex, data-driven full-stack software systems.",
                            ImagePath = "images/team/Anthony.jpg",
                            Name = "Anthony",
                            Role = "Lead Systems Developer"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
